import FooterComponent from "@/components/ui/footer.component";
import NavbarComponent from "@/components/ui/navbar.component";
import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";

import "./globals.css";

const font_init = Be_Vietnam_Pro({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-primary",
});

export const metadata: Metadata = {
  title: "MovieMate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font_init.variable}>
        <NavbarComponent />
        <div className="min-h-[80vh]">{children}</div>
        <FooterComponent />
      </body>
    </html>
  );
}
